@startuml
'https://plantuml.com/sequence-diagram

skinparam BackgroundColor #00000000

CPU -> "GPU Driver": Record Commands
activate "GPU Driver"
"GPU Driver" -> "GPU Driver": Store Commands in Buffer
return

CPU -> "GPU Driver": Submit Command Buffer
activate "GPU Driver"
"GPU Driver" -> "GPU Driver": Process
"GPU Driver" -> GPU: Submit Commands
activate GPU
GPU -> GPU: Execute Commands
GPU --> "GPU Driver": Response
deactivate GPU
"GPU Driver" --> CPU: Signal Semaphore
deactivate "GPU Driver"

CPU -> "GPU Driver": Present
activate "GPU Driver"
"GPU Driver" -> GPU: Present
activate GPU
GPU -> GPU: Present to Monitor
GPU --> "GPU Driver": Response
deactivate GPU
"GPU Driver" --> CPU: Signal Semaphore
deactivate "GPU Driver"

@enduml