@startuml
'https://plantuml.com/sequence-diagram

Engine -> VoxelRenderer: Record Commands
VoxelRenderer -> GeometryStage: Record Commands
GeometryStage --> VoxelRenderer: Return Geometry Buffer
VoxelRenderer --> DenoiserStage: Record Commands
DenoiserStage --> VoxelRenderer: Return Denoised Color
VoxelRenderer --> UpscalerStage: Record Commands
UpscalerStage --> VoxelRenderer: Return Upscaled Color
VoxelRenderer --> BlitStage: Record Commands
VoxelRenderer --> Engine:
Engine --> "GPU Driver": Submit Commands
"GPU Driver" --> Engine: Signal Semaphore

@enduml