@startuml

skinparam componentStyle rectangle
skinparam linetype polyline

skinparam nodesep 20
skinparam ranksep 20

skinparam BackgroundColor #00000000

together {
    (Scene 3D Texture) as SceneTex
    (Noise Texture) as NoiseTex
    (Geometry Params) as GeomParams
}

[Geometry Pass] as GeomPass

together {
    (Color) as ColorOut
    (Depth) as DepthOut
    (Motion) as MotionOut
    (Mask) as MaskOut
    (Position) as PosOut
    (Normal) as NormalOut
}

(Denoiser Parameters) as DenoiseParams

[Denoiser Pass] as DenoiserPass

(Denoised Color) as DenoiseOut

(Upscaler Parameters) as UpscalerParams

[Upscaler Pass] as UpscalerPass

(UpscaledOutput) as UpscaleOut

(Blit Parameters) as BlitParams

[Blit Pass] as BlitPass

(Swapchain Image) as Swapchain

SceneTex --> GeomPass
NoiseTex --> GeomPass
GeomParams --> GeomPass

GeomPass --> ColorOut
GeomPass --> DepthOut
GeomPass --> NormalOut
GeomPass --> PosOut
GeomPass --> MotionOut
GeomPass --> MaskOut

ColorOut --> DenoiserPass
PosOut --> DenoiserPass
NormalOut --> DenoiserPass
DenoiseParams --> DenoiserPass

DenoiserPass --> DenoiseOut

DenoiseOut --> UpscalerPass
DepthOut --> UpscalerPass
PosOut --> UpscalerPass
MotionOut --> UpscalerPass
MaskOut --> UpscalerPass
UpscalerParams --> UpscalerPass

UpscalerPass --> UpscaleOut

UpscaleOut --> BlitPass
BlitParams --> BlitPass

BlitPass --> Swapchain

@enduml